# Generated by Django 2.2.6 on 2020-03-10 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ABERTA', 'ABERTA'), ('FECHADA', 'FECHADA')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('macro_status', models.CharField(choices=[('APROVADO', 'APROVADO'), ('ELIMINADO', 'ELIMINADO'), ('PENDENTE', 'PENDENTE')], max_length=50)),
                ('micro_status', models.CharField(max_length=255)),
                ('progress', models.CharField(choices=[('FASE_1', 'FASE_1'), ('FASE_2', 'FASE_2'), ('FASE_3', 'FASE_3'), ('FASE_4', 'FASE_4'), ('FASE_5', 'FASE_5')], max_length=50)),
                ('positions', models.ManyToManyField(related_name='user', to='core.PositionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyMonkeyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('link_question', models.CharField(max_length=500)),
                ('link_answer', models.CharField(max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_monkey_quiz', to='core.PositionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_monkey_quiz', to='core.UserModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='', verbose_name='Curriculum File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='core.UserModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
