# Generated by Django 2.2.6 on 2020-03-10 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='progress',
        ),
        migrations.CreateModel(
            name='ProgressDetailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('stage', models.CharField(choices=[('FASE_1', 'FASE_1'), ('FASE_2', 'FASE_2'), ('FASE_3', 'FASE_3'), ('FASE_4', 'FASE_4'), ('FASE_5', 'FASE_5')], max_length=50)),
                ('feedback', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.UserModel')),
            ],
            options={
                'unique_together': {('user', 'stage')},
            },
        ),
    ]
