# Generated by Django 2.2.6 on 2020-03-10 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200310_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('link_questions', models.CharField(max_length=500)),
                ('link_answers', models.CharField(max_length=500)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.ProgressDetailModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizResultsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('partially_correct', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='core.QuizModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='micro_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together={('email',)},
        ),
        migrations.DeleteModel(
            name='SurveyMonkeyModel',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.UserModel'),
        ),
    ]
