# Generated by Django 2.2.6 on 2020-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200310_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='progress',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='stage',
            field=models.CharField(choices=[('FASE_1', 'FASE_1'), ('FASE_2', 'FASE_2'), ('FASE_3', 'FASE_3'), ('FASE_4', 'FASE_4'), ('FASE_5', 'FASE_5')], default='', max_length=50),
        ),
    ]
