# Generated by Django 2.2.6 on 2020-03-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200310_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressdetailmodel',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
