version: '3'

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /code/start-dev.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/code
    stdin_open: true
    tty: true
